title: BK Conference Deadlines
description: Countdowns to BK21+ Conference Deadlines
author: SeungHyun Han

domain: "aideadlin.es"
baseurl: ""

github_username: songhune
github_repo: bk-deadlines
forked info: "This project is forked from paperswithcode/ai-deadlines"
markdown: kramdown

include: ['_pages']
